# Generated by Django 5.1.3 on 2024-12-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pedido_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('litro', 'Litro'), ('gramo', 'Gramo'), ('kg', 'Kilogramo'), ('ml', 'Mililitro')], default='unidad', max_length=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='api.inventario')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='api.menu')),
            ],
        ),
    ]
